name = "ITensorBase"
uuid = "4795dd04-0d67-49bb-8f44-b89c448a1dc7"
authors = ["ITensor developers <support@itensor.org> and contributors"]
version = "0.4.0"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
DerivableInterfaces = "6c5e35bf-e59e-4898-b73c-732dcc4ba65f"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MapBroadcast = "ebd9b9da-f48d-417c-9660-449667d60261"
NamedDimsArrays = "60cbd0c0-df58-4cb7-918c-6f5607b73fde"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
TensorAlgebra = "68bd88dc-f39d-4e12-b2ca-f046b68fcc6a"
UnallocatedArrays = "43c9e47c-e622-40fb-bf18-a09fc8c466b6"
UnspecifiedTypes = "42b3faec-625b-4613-8ddc-352bf9672b8d"
VectorInterface = "409d34a3-91d5-4945-b6ec-7529ddf182d8"

[compat]
Accessors = "0.1.39"
ConstructionBase = "1.6.0"
DerivableInterfaces = "0.5"
FillArrays = "1.13"
LinearAlgebra = "1.10"
MapBroadcast = "0.1.5"
NamedDimsArrays = "0.10"
Random = "1.10"
TensorAlgebra = "0.3, 0.4, 0.5, 0.6"
UnallocatedArrays = "0.1.1"
UnspecifiedTypes = "0.1.1"
VectorInterface = "0.5"
julia = "1.10"

[workspace]
projects = ["benchmark", "dev", "docs", "examples", "test"]
