name = "ITensorBase"
uuid = "4795dd04-0d67-49bb-8f44-b89c448a1dc7"
authors = ["ITensor developers <support@itensor.org> and contributors"]
version = "0.4.4"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
NamedDimsArrays = "60cbd0c0-df58-4cb7-918c-6f5607b73fde"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
TensorAlgebra = "68bd88dc-f39d-4e12-b2ca-f046b68fcc6a"

[compat]
Accessors = "0.1.39"
ConstructionBase = "1.6.0"
NamedDimsArrays = "0.13"
Random = "1.10"
TensorAlgebra = "0.3, 0.4, 0.5, 0.6"
julia = "1.10"

[workspace]
projects = ["benchmark", "dev", "docs", "examples", "test"]
