[deps]
ITensorBase = "4795dd04-0d67-49bb-8f44-b89c448a1dc7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NamedDimsArrays = "60cbd0c0-df58-4cb7-918c-6f5607b73fde"

[sources.ITensorBase]
path = ".."

[compat]
ITensorBase = "0.5"
LinearAlgebra = "1.10"
NamedDimsArrays = "0.14"
